notebook:
    image: rockywei/jupyter
    ports: 
        - "8888:8888"
    volumes:
        - "./table_detection:/home:rw"
    working_dir: "/home"
    command: jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root --notebook-dir=/home
